#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

foo="bar"
ynh_app_setting_set --key=foo --value=$foo

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# BUILD SERVER
#=================================================
ynh_script_progression "Building $app..."

pushd $install_dir/server/
	ynh_hide_warnings ynh_exec_as_app CGO_ENABLED=0 go build -o $install_dir/
popd

ynh_safe_rm "$install_dir/.cache/"
ynh_safe_rm "$install_dir/go/"
ynh_safe_rm "$install_dir/.go-version"

#chmod +x "$install_dir/ente"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# BUILD WEB
#=================================================

pushd "$install_dir/web"
    ynh_hide_warnings ynh_exec_as_app yarn install
    ynh_hide_warnings ynh_exec_as_app yarn build:photos
    ynh_hide_warnings ynh_exec_as_app yarn build:accounts
    ynh_hide_warnings ynh_exec_as_app yarn build:auth
    ynh_hide_warnings ynh_exec_as_app yarn build:cast
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
